const moduleRouteMap = {
  CUENTA: "/cuenta",
  USUARIOS: "/usuarios",
  SUCURSALES: "/sucursales",
  AREAS: "/areas",
  MESAS: "/mesas",
  RESERVAS: "/reservas",
  RESERVAS_CLIENTE: "/reservas-cliente",
  ORDENES: "/ordenes",
  ORDENES_PICKUP: "/ordenes-pickup",
  CATEGORIAS: "/categorias",
  COMBOS: "/combos",
  PRODUCTOS_RECETA_COS: "/productos-recetas-costos",
  LIMPIEZA: "/limpieza",
  CLIENTE_EMPLEADO_CRM: "/crm",
  DASHBOARD: "/dashboard",
  AUDITORIA: "/auditoria",
  INSUMOS: "/insumos",
  PROVEEDORES: "/proveedores",
  UNIDADES_MEDIDA: "/unidades-medida",
  COMPRAS: "/compras",
  MERMAS: "/mermas",
  TICKETS: "/tickets",
  HORARIOS: "/horarios",
  ASISTENCIA: "/asistencia",
  BUZON_MEJORAS: "/buzon-mejoras",
  RECOMPENSAS_CLIENTE: "/recompensas-cliente",
  RECOMPENSAS_EMPLEADO: "/recompensas-empleado",
  COCINA: "/cocina",
  CONFIGURACION: "/configuracion",
  PAGOS: "/pagos"
};

export default moduleRouteMap;